"""added notifications

Revision ID: 046080d140ba
Revises: 58fa2ff8d504
Create Date: 2020-05-02 16:32:23.649970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046080d140ba'
down_revision = '58fa2ff8d504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
