"""photo chats

Revision ID: 4b9c96b4717f
Revises: 1f9aa7f7c1d7
Create Date: 2020-04-22 21:06:22.509593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9c96b4717f'
down_revision = '1f9aa7f7c1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
